[tasks.upload-server-cloudstation]
dependencies = ["build-server-aarch64"]
workspace = false
script = "scp target/aarch64-unknown-linux-gnu/release/shaysbot devs@cloudstation:/home/devs/.cargo/bin/shaysbot-temp"

[tasks.build-server-aarch64]
workspace = false
command = "cargo"
args = ["cross", "build", "--profile", "release", "--target", "aarch64-unknown-linux-gnu"]
